### ISSUE TITLE
compatibility_sweep in training.py needs to pass along device type to model_accuracy()

### ISSUE THREAD

**Issue by Nking92** [microsoft/BackwardCompatibilityML#23]
When the sweep_summary is created at the end of compatibility_sweep, the device type needs to be given to the model_accuracy() function. Otherwise it fails if you're running pytorch on the GPU.

The fix is pretty straightforward:

    sweep_summary = {
        "data": sweep_summary_data,
        "h1_performance": model_accuracy(h1, test_set, **device=device**)
    }

**Comment by ilmarinen** [comment]
Good catch. Thank you Nick.
