### ISSUE TITLE
Clicking Venn diagram intersection and on histogram column (or vice versa) does not filter Error Instances table by both choices

### ISSUE THREAD

**Issue by jlema** [microsoft/BackwardCompatibilityML#66]
Repro steps:
1. Open any of the MNIST example notebooks (or the dev harness), perform sweep.
2. Click on any data point on the scatter plots
3. Click on a column on the histogram (e.g. 4) and then on an intersection on the Venn diagram (e.g. progress.)
4. The error instances table only filters by progress instances.

Expected outcome: The error instances table filters both by class (4) and model error type (progress.)

Note: If a user clicks first on the Venn diagram intersection then on the histogram column it should have the same effect (filtering by both choices.)

Example: On the image below, we'd expect to see Progress instances for only class 4, but we only see progress instances.

![image](https://user-images.githubusercontent.com/9736891/98765233-82b48c80-2392-11eb-8d15-b1f6d129cb83.png)

**Comment by ilmarinen** [comment]
@jlema I think we discussed this earlier. I do not think that it makes sense to combine these filters. Here is the reason:

1. The Venn diagram is explicitly across all classes.
2. The Bar chart is per class.

I think what you intend here is rather that clicking on the Venn diagram should unset the selection on the bar chart.
And clicking on the bar chart should unset the selection on the Venn diagram.
